### ISSUE TITLE
Github user name bug

### ISSUE THREAD

**Issue by ianignacioa** [ianignacioa/mms142-groupa-2020.github.io#1]
I encountered a bug in Github. My username got changed, thus everytime I commit and push, a username of 'ianiganacioa' was recorded as seen in the contribution insights.

**Comment by keanaquino** [comment]
As far as I know now how to config the git. Did you try to check your user.name and user.email in the command `git config --list`?

**Comment by shaniaamores** [comment]
I think this is already fixed, see the commit history..
