### ISSUE TITLE
css file template

### ISSUE THREAD

**Issue by mariajenggay** [ianignacioa/mms142-groupa-2020.github.io#4]
Are some of the files in the  `lib` folder necessary?

**Comment by ianignacioa** [comment]
> Are some of the files in the `lib` folder necessary?

Yes, they are the workers for the functionality of the webpages.😊

**Comment by ianignacioa** [comment]
We won't change it anymore for the final submission.

**Comment by mariajenggay** [comment]
So we will not change it anymore for final submission? 🤔

**Comment by ianignacioa** [comment]
> So we will not change it anymore for final submission? 🤔

Yes! There'll be no further changes.
