### ISSUE TITLE
Bug on contributor raw button in the README.md file

### ISSUE THREAD

**Issue by mariajenggay** [ianignacioa/mms142-groupa-2020.github.io#5]
**Describe the bug**

Look at the README.md,only two contributors are counted.

**Additional context**

Is there a way to fix it?

**Comment by ianignacioa** [comment]
Ok, wait. Let me check. I think I'll be changing it using shields.io .

**Comment by ianignacioa** [comment]
You should commit and push more so your record will go higher, and eventually, you will be displayed as one of the contributors.

**Comment by mariajenggay** [comment]
Okay thank you!😊 I will try to check some bugs ang configure it out so that I can commit and push again.

**Comment by mariajenggay** [comment]
Already fixed, 3 contributors are now counted.😃
