### ISSUE TITLE
How to pull request?

### ISSUE THREAD

**Issue by keanaquino** [ianignacioa/mms142-groupa-2020.github.io#6]
I would like to ask how to pull request here?

**Comment by ajrandaya** [comment]
Create a new branch in your workspace, if you are getting confused follow the command given in the CONTRIBUTING section, make sure you already install the git software on your computer. After installing the git software open it and follow the steps in the CONTRIBUTING section.

**Comment by keanaquino** [comment]
okay thank you bro!

**Comment by shaniaamores** [comment]
Please close the issue and vote!
